source 'http://rubygems.org'

gem 'rails', '~> 4.0.0.beta1', github: 'rails/rails'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem "sorcery", '>= 0.1.0', :path => '../'
gem 'oauth'
gem 'oauth2'
group :development do
  gem "rspec"
end
